### ISSUE TITLE
Error with Beaker in Mongo Module

### ISSUE THREAD

**Issue by petems** [puppetlabs/beaker-rspec#40]
`$ bundle exec rspec spec/acceptance/server_spec.rb`

```
/opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec/beaker_shim.rb:35:in `validate': uninitialized constant Beaker::Utils (NameError)
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec/spec_helper.rb:22:in `block in <top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core.rb:79:in `configure'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec.rb:5:in `require'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-2.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
	from /Users/peterso/Projects/puppetlabs-mongodb/spec/spec_helper_acceptance.rb:2:in `require'
	from /Users/peterso/Projects/puppetlabs-mongodb/spec/spec_helper_acceptance.rb:2:in `<top (required)>'
	from /Users/peterso/Projects/puppetlabs-mongodb/spec/acceptance/server_spec.rb:1:in `require'
	from /Users/peterso/Projects/puppetlabs-mongodb/spec/acceptance/server_spec.rb:1:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/configuration.rb:1051:in `load'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/configuration.rb:1051:in `block in load_spec_files'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/configuration.rb:1051:in `each'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/configuration.rb:1051:in `load_spec_files'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:97:in `setup'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:85:in `run'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:70:in `run'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/lib/rspec/core/runner.rb:38:in `invoke'
	from /opt/boxen/rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-3.0.0/exe/rspec:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.0.0-p451/bin/rspec:23:in `load'
	from /opt/boxen/rbenv/versions/2.0.0-p451/bin/rspec:23:in `<main>'
```

**Comment by anodelman** [comment]
This issue was resolved.
